# Generated by Django 3.2 on 2021-05-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categooory', models.CharField(max_length=300)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='episodesss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent_serie', models.CharField(max_length=300)),
                ('episode', models.URLField()),
                ('episode_number', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='main_poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='upload_serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_width1600', models.URLField()),
                ('min_width1440', models.URLField()),
                ('min_width960', models.URLField()),
                ('min_width600', models.URLField()),
                ('img', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('image_description', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=200)),
                ('korean_title', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('genres', models.CharField(max_length=300)),
                ('cast', models.CharField(max_length=300)),
                ('episodes', models.IntegerField()),
                ('category', models.CharField(max_length=300)),
            ],
        ),
    ]
