# Generated by Django 3.2 on 2021-06-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_serie',
            name='korean_title',
        ),
    ]
