# Generated by Django 3.2 on 2021-05-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0002_auto_20210524_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodesss',
            name='onlyepisodenumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
