# Generated by Django 3.2 on 2021-05-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0003_episodesss_onlyepisodenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='epi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_url', models.CharField(max_length=300)),
                ('epi_no', models.IntegerField()),
                ('epi_url', models.URLField()),
            ],
        ),
    ]
