# Generated by Django 3.2 on 2021-05-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0004_epi'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodesss',
            name='parent_url',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
