# Generated by Django 3.2 on 2021-05-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0006_auto_20210525_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodesss',
            name='subtitle',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
