# Generated by Django 3.2 on 2021-05-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0007_episodesss_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodesss',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='episodesss',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='episodesss',
            name='video_embed',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
