# Generated by Django 3.2 on 2021-05-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0008_auto_20210525_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_serie',
            name='category',
        ),
    ]
