# Generated by Django 3.2 on 2021-05-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0009_remove_upload_serie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_serie',
            name='keywords',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
