# Generated by Django 3.2 on 2021-05-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0013_auto_20210530_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category10_name',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='category1_name',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='category2_name',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='category3_name',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='category4_name',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='category5_name',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='category6_name',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='category7_name',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='category8_name',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='category9_name',
            name='classify',
        ),
    ]
