# Generated by Django 3.2 on 2021-06-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0014_auto_20210530_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_serie',
            name='keywords',
        ),
    ]
