# Generated by Django 3.2 on 2021-06-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0015_remove_upload_serie_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=300)),
                ('episode_watching', models.URLField()),
            ],
        ),
    ]
