# Generated by Django 3.2 on 2021-06-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0016_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='episode_watching',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_ip',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
