# Generated by Django 3.2 on 2021-06-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0017_auto_20210611_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='episode_watching',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='episode_watching1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='episode_watching10',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='episode_watching2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='episode_watching3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='episode_watching4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='episode_watching5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='episode_watching6',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='episode_watching7',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='episode_watching8',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='episode_watching9',
            field=models.URLField(blank=True, null=True),
        ),
    ]
