# Generated by Django 3.2 on 2021-06-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0018_auto_20210611_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='episode_watching1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='episode_watching10',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='episode_watching2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='episode_watching3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='episode_watching4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='episode_watching5',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='episode_watching6',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='episode_watching7',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='episode_watching8',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='episode_watching9',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
