# Generated by Django 3.2 on 2021-06-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0019_auto_20210611_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(blank=True, max_length=300, null=True)),
                ('episode_watching', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
