# Generated by Django 3.2 on 2021-06-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kdrama', '0020_auto_20210611_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertracker',
            name='img',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertracker',
            name='title',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
